name: SSH Server Deploy
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.x

      - name: build
        run: |
          npm i pnpm -g
          pnpm i
          pnpm run build

      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: 192.241.148.118
          port: 22
          username: root
          password: passW0rd
          scp_source: ./dist/*
          scp_target: /var/www/
          after_script: |
            whoami
